library(blogdown)
serve_site()
build_site()
blogdown::clean_site()
hugo_version()
stop_server()
stop_server()
find_hugo()
options(blogdown.hugo.executable = "C:/Users/eb/AppData/Roaming/Hugo/0.80.0/hugo.exe")
file.exists("C:/Users/eb/AppData/Roaming/Hugo/0.96.0/hugo.exe")
options(blogdown.hugo.executable = "C:/Users/eb/AppData/Roaming/Hugo/0.96.0/hugo.exe")
getOption("blogdown.hugo.executable")
usethis::edit_r_profile()
stop_server()
